spring:
  application:
    name: config-management-server

  profiles:
    active: vault,native

  cloud:
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          authentication: token
          token: c54cde87-7570-4349-84c0-6cb48d53d8e9
          kv-version: 2
          backend: secret
          order: 1
        native:
          search-locations: classpath:/configurations/demo-service
          order: 2

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

server:
  port: 8071
